### PR TITLE
Resource estimation with EXORCISM-4

### PR DESCRIPTION
**Pull request by glassnotes**
This PR contains Python scripts and some csv data files of experiments creating random qROMs and then running them through a logic synthesis optimization tool (EXORCISM-4) to get resource counts. 

These resource counts are still not totally optimal (there is no further Clifford+T decomposition or simplification of the optimized circuits) but this is a better estimate than the ones done in [our original work](https://arxiv.org/abs/1902.01329).

### CODE REVIEW

**Comment by glassnotes** [comment]
Note: this requires the [`abc` executable](https://github.com/berkeley-abc/abc) to reproduce the csv files.

Not sure how we want to incorporate this in the library at large (or if we want to incorporate it at all).

**Comment by msoeken** [comment]
@glassnotes There is a reimplementation of exorcism [here](https://github.com/boschmitt/exorcism) with much less overhead than abc.

There is also a library extraction of only the exorcism code from abc [here](https://github.com/lsils/mockturtle/tree/master/lib/abcesop)

**Comment by glassnotes** [comment]
@msoeken Aha, I knew it must have been in the EPFL libraries somewhere! Thank you for the links, I will take a look. It would definitely be nice to use something more streamlined.

(BTW - that command in `abc.md` is actually one that you sent me in an e-mail like > 2.5 years ago when I first started working on qRAM :grin: )

**Comment by crazy4pi314** [comment]
@msoeken I think we would love to figure out how to actually include this in the Q# library or simulator feature there without having to call out to external code. What approach would you take for this? Add it as part of like the Toffli simulator?

**Review by crazy4pi314 — APPROVED** [review]
Fab as always ✨😺

**Pull request merged**
