### PR TITLE
Select network based on unary iteration

### PR DESCRIPTION
**Pull request by msoeken**
This PR implements the table lookup procedure described in [arXiv:1805.03662, Section 3A](https://arxiv.org/abs/1805.03662).

* [x] Implementation
* [x] Tests
* [x] Docs

### CODE REVIEW

**Comment by crazy4pi314** [comment]
Super excited for this, let me know how I can help!

**Comment by msoeken** [comment]
Thanks @crazy4pi314! I have added the missing documentation, and from my side the PR is ready for review.

**Comment by msoeken** [comment]
Hi @crazy4pi314, is there anything from my side to help merging this PR?

**Review by crazy4pi314 — APPROVED** [review]
LGTM! Sorry for the delay, I was busy running unitaryHACK and all the close out on <3

**Comment by crazy4pi314** [comment]
I'll kick off a new release with this asap!

**Pull request merged**
